# Generated by Django 5.2.3 on 2025-07-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationsReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote_date', models.DateField(auto_now_add=True)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasingOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Issued', max_length=10)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.quotationsreceived')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField()),
                ('requested_by', models.CharField(max_length=100)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('vendor_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Responded', 'Responded'), ('Closed', 'Closed')], default='Sent', max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='quotationsreceived',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.requestforquotes'),
        ),
    ]
